### ISSUE TITLE
Improve error reporting of `ExpressionPaser`

### ISSUE THREAD

**Issue by renggli** [petitparser/dart-petitparser#143]
The default error reporting of the `ExpressionBuilder` is not ideal. It reports the last error seen, not necessarily the most specific one. There should be some way to configure custom error handling behavior, like for the choice parsers. For context see https://stackoverflow.com/questions/75503464.

**Comment by renggli** [comment]
Note: The above improvements depend on a rewrite of the underlying (and internal) execution model of PetitParser (in branch [mutable-context](https://github.com/petitparser/dart-petitparser/tree/mutable-context)), so it is rather a deep change that will need some more testing until it might make it into the next major version.

Please have a try by updating your dependencies to:

```yaml
dependencies:
  petitparser:
    git:
      url: https://github.com/petitparser/dart-petitparser.git
      ref: mutable-context
```
