### ISSUE TITLE
package:matcher (or maybe package:test) must be declared as a public dependency

### ISSUE THREAD

**Issue by scheglov** [petitparser/dart-petitparser#53]
The library `lib/test.dart` has import `import 'package:matcher/matcher.dart';`.

This means that the package `matcher` must be a public dependency, not

```
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  test: '>=0.12.1 <0.13.0'
```

This prevents Analysis Server from building linked summaries for the package `petitparser` and the transitive list of packages that use it.

@bwilkerson @stereotype441 @kevmoo

**Comment by renggli** [comment]
Fixed in c9dc90bc67442329fb14c21ae693dbe3a70e9357.

**Comment by scheglov** [comment]
Sigh...
That's not what I would expect.

We need to move `test` from `dev_dependencies` to `dependencies`.
Or remove `lib/test.dart`.

And it seems to me that `package:browser` is never imported by `petitparser`.

```
name: petitparser
version: 1.6.0
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/dart-petitparser
environment:
  sdk: ^1.8.0
dependencies:
  test: ^0.12.0
```

@kevmoo
